#!/bin/bash
#SBATCH -p gpu_short
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate wsdartscuda9
python train_unaligned.py --train-root-dir=~/facenet_pytorch/datasets/CASIA/CASIA-maxpy-clean --valid-root-dir=~/facenet_pytorch/datasets/vggface2_test/aligned --train-csv-name=~/facenet_pytorch/datasets/CASIA.csv --valid-csv-name=~/facenet_pytorch/datasets/test_vggface2.csv
source deactivate