#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
source deactivate
python train.py --pure_training --num-epochs=140 --start-epoch=60 --load_pth_from=./log/20191009-125246/ --save_pth_to_separate_dir --train_format=.png --valid_format=.png --train-root-dir=/lustre2/0/wsdarts/datasets/CASIA_aligned_split_correctly/train/ --valid-root-dir=/lustre2/0/wsdarts/datasets/CASIA_aligned_split_correctly/val/ --train-csv-name=/nfs/home4/mhouben/facenet_pytorch/datasets/CASIA_train.csv --valid-csv-name=~/facenet_pytorch/datasets/CASIA_test.csv --train_dataset_depth=3 --val_dataset_depth=3