#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python train.py --train_format=.png --valid_format=.png --num-epochs=112 --start-epoch=88 --load_pth_from=./log/20190910-165231/ --save_pth_to_separate_dir --train-root-dir=/lustre2/0/wsdarts/datasets/omniglot_1_folder_splits/train/ --valid-root-dir=/lustre2/0/wsdarts/datasets/omniglot_1_folder_splits/val/ --train-csv-name=~/facenet_pytorch/datasets/omniglot_train_1_folder.csv --valid-csv-name=~/facenet_pytorch/datasets/omniglot_val_1_folder.csv --num-classes=487 --train_dataset_depth=1 --val_dataset_depth=1
source deactivate