#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
source deactivate
python train.py --pure_validation --start-epoch=196 --save_pth_to_separate_dir --load_pth_from=/lustre2/0/wsdarts/facenet_logs/20191010-141847 --train_format=.png --valid_format=.png --train-root-dir="/lustre2/0/wsdarts/datasets/omniglot_multiple_folders_split/train/Mkhedruli_(Georgian)/" --valid-root-dir="/lustre2/0/wsdarts/datasets/omniglot_multiple_folders_split/val/Mkhedruli_(Georgian)/" --train-csv-name="/nfs/home4/mhouben/facenet_pytorch/datasets/omniglot_alphabet_csvs/train/Mkhedruli_(Georgian).csv" --valid-csv-name="/nfs/home4/mhouben/facenet_pytorch/datasets/omniglot_alphabet_csvs/val/Mkhedruli_(Georgian).csv" --train_dataset_depth=1 --val_dataset_depth=1 --num-valid-triplets=10 --batch-size=1