#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 50:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate wsdartscuda9
python train.py --train-root-dir=~/facenet_pytorch/datasets/vggface2_train/vggface2_train_aligned --valid-root-dir=~/facenet_pytorch/datasets/vggface2_test/vggface2_test_aligned  --image_size=182 --margin=44
source deactivate