#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
source deactivate
python train.py --pure_training --train_format=.png --valid_format=.png --train-root-dir=/lustre2/0/wsdarts/datasets/cifar/train/ --valid-root-dir=/lustre2/0/wsdarts/datasets/cifar/val/ --train-csv-name=/nfs/home4/mhouben/facenet_pytorch/datasets/cifar_train.csv --valid-csv-name=~/facenet_pytorch/datasets/cifar_test.csv --train_dataset_depth=3 --val_dataset_depth=3