#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python train.py --train_dataset_depth=1 --pure_training --train_torchvision --train-root-dir=/lustre2/0/wsdarts/jpg_datasets/mnist/train --train-csv-name=/nfs/home4/mhouben/classic_net_runs/mnist_train.csv --num-classes=10
source deactivate