#!/bin/bash
#SBATCH -p gpu_short
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate wsdartscuda9
python train_unaligned.py --train-root-dir=~/facenet_pytorch/datasets/vggface2_train/unaligned --valid-root-dir=~/facenet_pytorch/datasets/vggface2_test/vggface2_test_unaligned --train-csv-name=~/facenet_pytorch/datasets/train_vggface2.csv --valid-csv-name=~/facenet_pytorch/datasets/test_vggface2.csv
source deactivate