#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python train.py --train_dataset_depth=1 --val_dataset_depth=3 --valid_format=.png --train-root-dir=/lustre2/0/wsdarts/datasets/omniglot_1_folder/ --valid-root-dir=/lustre2/0/wsdarts/datasets/lfw_aligned/ --train-csv-name=~/facenet_pytorch/datasets/omniglot_1_folder.csv --valid-csv-name=~/facenet_pytorch/datasets/lfw.csv
source deactivate