#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python train.py --pure_validation --train_format=.png --valid_format=.png --start-epoch=196 --load_pth_from=./log/20190923-110007/ --save_pth_to_separate_dir --valid-root-dir=/lustre2/0/wsdarts/datasets/inaturalist_2019/val/Reptiles/ --valid-csv-name=/nfs/home4/mhouben/facenet_pytorch/datasets/inaturalist2019_alphabet_csvs/val/Reptiles.csv --train_dataset_depth=3 --val_dataset_depth=3
source deactivate
