#!/bin/bash
#SBATCH -p gpu
#SBATCH -t 100:00:00
bash $HOME/miniconda3/etc/profile.d/conda.sh
source activate pytorch11
python train.py --pure_validation --train_format=.png --valid_format=.png --start-epoch=191 --load_pth_from=./log/20190914-155441/ --save_pth_to_separate_dir --train-root-dir=/lustre2/0/wsdarts/datasets/omniglot_1_folder_splits/train/ --valid-root-dir=/lustre2/0/wsdarts/datasets/inaturalist_2019/val/Amphibians/ --train-csv-name=~/facenet_pytorch/datasets/omniglot_train_1_folder.csv --valid-csv-name=/nfs/home4/mhouben/facenet_pytorch/datasets/inaturalist2019_alphabet_csvs/val/Amphibians.csv --num-classes=487 --train_dataset_depth=1 --val_dataset_depth=3
source deactivate